---
- hosts: default
  become: true
  vars:
    server_color: "{{ bg_color }}"
  tasks:
    - name: Update the apt-get
      apt:
        update_cache: yes

    - name: Install apache2
      apt:
        name: "apache2"
        state: present

    - name: Create a directory if it does not exist
      file:
        path: "/var/www/{{ bg_color }}"
        state: directory

    - name: Copy new template index.html.j2 file
      template:
        src: "index.html.j2"
        dest: "/var/www/{{ bg_color }}/index.html"

    - name: Copy configuration file for apache2
      copy:
        src: "{{ bg_color }}.conf"
        dest: "/etc/apache2/sites-available/{{ bg_color }}.conf"

    - name: Disable site for default.conf
      command:
        a2dissite 000-default.conf

    - name: Enable site for {{ bg_color }}.conf
      command:
        a2ensite {{ bg_color }}.conf

    - name: Restart apache2 server
      service:
        name: apache2
        state: restarted